[functions.cloudflare-stream-upload-url]
verify_jwt = false

[functions.cloudflare-stream-playback-token]
verify_jwt = false

[functions.cloudflare-stream-delete-video]
verify_jwt = false

[functions.admin-memberships]
verify_jwt = false
