import { useCallback, useEffect, useState } from 'react'
import { adminRequest } from '../lib/admin-control-center'

const labels={visible:'Viditeľný',hidden:'Skrytý',deleted:'Odstránený'}
const date=(value)=>new Intl.DateTimeFormat('sk-SK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))

export default function AdminVideoComments({video,onBack,onChanged}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[busy,setBusy]=useState('')
  const load=useCallback(async()=>{setLoading(true);try{setData(await adminRequest({action:'video-comments',videoId:video.id,status,search,limit:50}));setError('')}catch(loadError){setError(loadError.message)}finally{setLoading(false)}},[search,status,video.id])
  useEffect(()=>{const timer=window.setTimeout(load,search?300:0);return()=>window.clearTimeout(timer)},[load,search])
  const moderate=async(commentId,operation)=>{if(busy)return;setBusy(commentId);try{await adminRequest({action:'moderate-video-comment',commentId,operation});await load();onChanged?.()}catch(actionError){setError(actionError.message)}finally{setBusy('')}}
  return <section className="admin-video-comments"><button className="admin-back" type="button" onClick={onBack}>← Späť na videá</button><div className="admin-page-heading"><div><span>ADMIN / VIDEO / KOMENTÁRE</span><h1>{video.title}</h1><p>Moderácia reálnych komentárov a prehľad interakcií.</p></div></div><div className="admin-toolbar"><input type="search" placeholder="Hľadať v komentároch" value={search} onChange={(event)=>setSearch(event.target.value)}/><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="all">Všetky stavy</option><option value="visible">Viditeľné</option><option value="hidden">Skryté</option><option value="deleted">Odstránené</option></select><span>{data?.total??'—'} komentárov</span></div>{error&&<p className="admin-alert is-error" role="alert">{error}</p>}{loading&&!data?<div className="admin-loading"><i/>Načítavam komentáre…</div>:data?.comments?.length?<div className="admin-comment-list">{data.comments.map((comment)=><article key={comment.id}><header><div><strong>{comment.username}</strong><small>{date(comment.created_at)} · {comment.videoTitle}</small></div><span className={`is-${comment.status}`}>{labels[comment.status]}</span></header><p>{comment.body}</p><footer>{comment.status==='visible'&&<button type="button" disabled={busy===comment.id} onClick={()=>moderate(comment.id,'hide')}>Skryť</button>}{comment.status!=='visible'&&<button type="button" disabled={busy===comment.id} onClick={()=>moderate(comment.id,'restore')}>Znovu zobraziť</button>}{comment.status!=='deleted'&&<button className="is-danger" type="button" disabled={busy===comment.id} onClick={()=>moderate(comment.id,'delete')}>Odstrániť</button>}</footer></article>)}</div>:!loading&&<div className="admin-empty">Žiadne komentáre v tomto filtri.</div>}</section>
}
