import { useCallback,useEffect,useState } from 'react'
import { cachedAdminLoad,invalidateAdminCache,readAdminCache } from '../lib/admin-cache'
import { collaborationAdminRequest } from '../lib/collaborations'
const states=['new','contacted','negotiating','agreed','rejected','archived']
const labels={new:'Nová',contacted:'Kontaktovaná',negotiating:'Rokovanie',agreed:'Dohodnutá',rejected:'Odmietnutá',archived:'Archivovaná'}
const date=(v)=>v?new Intl.DateTimeFormat('sk-SK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'Nedostupné'
function navigate(path){history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))}

function Detail({id}){
 const key=`collaboration:${id}`,cached=readAdminCache(key),[hadCached]=useState(Boolean(cached)),[data,setData]=useState(cached),[loading,setLoading]=useState(!cached),[error,setError]=useState(''),[sending,setSending]=useState(false),[notice,setNotice]=useState('')
 const load=useCallback(async(force=false)=>{const result=await cachedAdminLoad(key,()=>collaborationAdminRequest({action:'detail',id}),{force});setData(result);setLoading(false)},[id,key])
 useEffect(()=>{load(hadCached).catch((e)=>{setError(e.message);setLoading(false)})},[load,hadCached])
 if(loading&&!data)return <div className="admin-loading"><i/>Načítavam spoluprácu…</div>
 if(error&&!data)return <div className="admin-empty">{error}</div>
 const item=data.request
 const change=async(status)=>{try{await collaborationAdminRequest({action:'status',id,status});invalidateAdminCache(key,'collaboration-summary');await load(true)}catch(e){setError(e.message)}}
 const reply=async(e)=>{e.preventDefault();if(sending)return;const formElement=e.currentTarget,form=new FormData(formElement);setSending(true);setNotice('');try{await collaborationAdminRequest({action:'reply',id,subject:form.get('subject'),message:form.get('message')});formElement.reset();invalidateAdminCache(key,'collaboration-summary');await load(true);setNotice('Odpoveď bola odoslaná.')}catch(err){setNotice(err.message)}finally{setSending(false)}}
 return <section><button className="admin-back" onClick={()=>navigate('/admin/collaborations')}>← Spolupráce</button><div className="admin-page-heading"><div><span>ADMIN / SPOLUPRÁCE</span><h1>{item.name}</h1><p>{item.company||item.email}</p></div></div>{error&&<p className="admin-alert is-error">{error}</p>}<div className="admin-detail-grid"><article className="admin-panel"><h2>Informácie</h2><dl className="admin-detail-list">{[['E-mail',item.email],['Firma',item.company||'Nedostupné'],['Telefón',item.phone||'Nedostupné'],['Predmet',item.subject],['Rozpočet',item.budget||'Nedostupné'],['Prijaté',date(item.created_at)]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></article><article className="admin-panel"><h2>Stav</h2><select className="admin-collaboration-status" value={item.status} onChange={(e)=>change(e.target.value)}>{states.map((s)=><option value={s} key={s}>{labels[s]}</option>)}</select><h2 className="admin-collaboration-subheading">Pôvodná správa</h2><p className="admin-collaboration-message">{item.message}</p></article></div><article className="admin-panel admin-detail-section"><h2>História komunikácie</h2><div className="admin-conversation">{data.messages.map((m)=><div className={`is-${m.direction}`} key={m.id}><small>{m.direction==='incoming'?'ZÁUJEMCA':'VÝCHOD BROTHERS'} · {date(m.created_at)} · {m.delivery_status}</small><strong>{m.subject}</strong><p>{m.body}</p></div>)}</div></article><article className="admin-panel admin-detail-section"><h2>Odoslať odpoveď</h2><form className="admin-collaboration-reply" onSubmit={reply}><label>Predmet<input name="subject" defaultValue={`Re: ${item.subject}`} required maxLength="180" /></label><label>Odpoveď<textarea name="message" rows="7" required maxLength="10000" /></label><button disabled={sending}>{sending?'ODOSIELAM…':'ODOSLAŤ ODPOVEĎ'}</button><p aria-live="polite">{notice}</p></form></article></section>
}

function List(){
 const [status,setStatus]=useState('all'),[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[data,setData]=useState(null),[error,setError]=useState('')
 useEffect(()=>{const timer=setTimeout(()=>setDebounced(search.trim()),300);return()=>clearTimeout(timer)},[search])
 useEffect(()=>{let active=true;const key=`collaboration-list:${status}:${debounced}`;cachedAdminLoad(key,()=>collaborationAdminRequest({action:'list',status,search:debounced,limit:50})).then((r)=>active&&setData(r)).catch((e)=>active&&setError(e.message));return()=>{active=false}},[status,debounced])
 return <section><div className="admin-page-heading"><div><span>ADMIN / CRM</span><h1>Spolupráce</h1><p>Reálne ponuky prijaté cez webový formulár.</p></div></div><div className="admin-toolbar"><input type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Meno, firma alebo e-mail"/><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">Všetky stavy</option>{states.map((s)=><option value={s} key={s}>{labels[s]}</option>)}</select><span>{data?.total??'—'} výsledkov</span></div>{error&&<p className="admin-alert is-error">{error}</p>}{!data&&!error?<div className="admin-loading"><i/>Načítavam spolupráce…</div>:data?.requests.length?<div className="admin-table-wrap"><table><thead><tr><th>Záujemca</th><th>Predmet</th><th>Dátum</th><th>Stav</th></tr></thead><tbody>{data.requests.map((r)=><tr className="is-clickable" key={r.id} onClick={()=>navigate(`/admin/collaborations/${r.id}`)}><td><strong>{r.name}{r.status==='new'&&<b className="admin-new-badge">NOVÉ</b>}</strong><small>{r.company||r.email}</small></td><td>{r.subject}</td><td>{date(r.created_at)}</td><td>{labels[r.status]}</td></tr>)}</tbody></table></div>:data&&<div className="admin-empty">Žiadne spolupráce v tomto filtri.</div>}</section>
}
export default function AdminCollaborations({id}){return id?<Detail id={id}/>:<List/>}
