import { useCallback, useEffect, useMemo, useState } from 'react'
import { cachedAdminLoad, readAdminCache } from '../lib/admin-cache'
import { getAdminAnalytics } from '../lib/analytics'

const ranges=[['24h','24 hodín'],['7d','7 dní'],['30d','30 dní'],['90d','90 dní'],['12m','12 mesiacov']]
const number=(value)=>new Intl.NumberFormat('sk-SK').format(Number(value)||0)
const comparison=(current,previous)=>previous>0?`${current>=previous?'+':''}${Math.round(((current-previous)/previous)*100)} %`:current>0?'Nové dáta':'—'
const label=(value,range)=>new Intl.DateTimeFormat('sk-SK',range==='24h'?{hour:'2-digit'}:range==='12m'?{month:'short'}:{day:'numeric',month:'short'}).format(new Date(value))

function Metric({title,value,detail,live}){return <article className={`admin-analytics-metric${live?' is-live':''}`}><span>{live&&<i/>}{title}</span><strong>{number(value)}</strong><small>{detail}</small></article>}
function Bars({data,range}){const max=Math.max(1,...data.map((d)=>Math.max(Number(d.pageviews),Number(d.uniques))));return <div className="admin-analytics-chart" role="img" aria-label="Graf unikátnych návštevníkov a page views"><div className="admin-chart-legend"><span><i className="is-pages"/>Page views</span><span><i className="is-unique"/>Unikátni návštevníci</span></div><div className="admin-chart-bars">{data.map((item)=><div className="admin-chart-column" key={item.bucket} title={`${label(item.bucket,range)}: ${item.pageviews} page views, ${item.uniques} unikátnych`}><div><i className="is-pages" style={{height:`${Math.max(2,Number(item.pageviews)/max*100)}%`}}/><i className="is-unique" style={{height:`${Math.max(2,Number(item.uniques)/max*100)}%`}}/></div><small>{label(item.bucket,range)}</small></div>)}</div></div>}
function Breakdown({title,rows,nameKey,valueKey='visits'}){const total=rows.reduce((sum,row)=>sum+Number(row[valueKey]||0),0);return <article className="admin-panel admin-analytics-breakdown"><h2>{title}</h2>{rows.length?rows.map((row)=><div key={row[nameKey]}><span>{row[nameKey]}</span><b>{number(row[valueKey])}</b><small>{total?Math.round(Number(row[valueKey])/total*100):0} %</small><i><em style={{width:`${total?Number(row[valueKey])/total*100:0}%`}}/></i></div>):<p>Dáta zatiaľ nie sú dostupné.</p>}</article>}

export default function AdminAnalytics(){
 const [range,setRange]=useState('7d'),cached=readAdminCache('admin-analytics:7d'),[data,setData]=useState(cached),[loading,setLoading]=useState(!cached),[error,setError]=useState('')
 const load=useCallback(async(nextRange=range,force=false)=>{try{const result=await cachedAdminLoad(`admin-analytics:${nextRange}`,()=>getAdminAnalytics(nextRange),{force});setData(result);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}},[range])
 useEffect(()=>{setLoading(!readAdminCache(`admin-analytics:${range}`));load(range)},[range,load])
 useEffect(()=>{const timer=setInterval(()=>load(range,true),30000);return()=>clearInterval(timer)},[range,load])
 const s=data?.summary,metrics=useMemo(()=>s?[['Návštevníci dnes',s.today.visitors,comparison(s.today.visitors,s.yesterday.visitors)+' oproti včerajšku'],['Unikátni dnes',s.today.uniques,comparison(s.today.uniques,s.yesterday.uniques)+' oproti včerajšku'],['Page views dnes',s.today.pageviews,comparison(s.today.pageviews,s.yesterday.pageviews)+' oproti včerajšku'],['Návštevníci včera',s.yesterday.visitors,'uzavreté obdobie'],['Tento týždeň',s.week.visitors,comparison(s.week.visitors,s.previousWeek.visitors)+' oproti minulému týždňu'],['Tento mesiac',s.month.visitors,comparison(s.month.visitors,s.previousMonth.visitors)+' oproti minulému mesiacu']]:[],[s])
 return <section><div className="admin-page-heading"><div><span>ADMIN / ANALYTICS</span><h1>Analytika webu</h1><p>Reálne anonymizované návštevnostné dáta od začiatku merania.</p></div>{data?.trackingSince&&<time>Meranie od {new Intl.DateTimeFormat('sk-SK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.trackingSince))}</time>}</div>{error&&<p className="admin-alert is-error">{error}</p>}{loading&&!data?<div className="admin-loading"><i/>Načítavam analytiku…</div>:data&&<><div className="admin-analytics-metrics"><Metric title="PRÁVE ONLINE" value={data.online} detail="aktívni za posledných 90 sekúnd" live/>{metrics.map(([title,value,detail])=><Metric title={title} value={value} detail={detail} key={title}/>)}</div><article className="admin-panel admin-analytics-traffic"><header><div><span>NÁVŠTEVNOSŤ WEBU</span><h2>Historický vývoj</h2></div><div className="admin-range-tabs">{ranges.map(([key,text])=><button className={range===key?'is-active':''} onClick={()=>setRange(key)} key={key}>{text}</button>)}</div></header><Bars data={data.chart||[]} range={range}/></article><div className="admin-analytics-grid"><Breakdown title="Najnavštevovanejšie stránky" rows={data.pages||[]} nameKey="path" valueKey="pageviews"/><Breakdown title="Zdroje návštevnosti" rows={data.sources||[]} nameKey="source"/><Breakdown title="Zariadenia" rows={data.devices||[]} nameKey="device"/><Breakdown title="Práve navštívené stránky" rows={data.onlinePages||[]} nameKey="path" valueKey="visitors"/></div></>}</section>
}
